POST http://localhost:8080/user-api/user
Content-Type: application/json

{
    "name":"ravi",
    "email":"ravi13@mail.com",
    "password":"ravi"
}

###Login
POST http://localhost:8080/user-api/login
Content-Type: application/json

{
    "email":"ravi13@mail.com",
    "password":"ravi"
}

### Add new todo
POST http://localhost:8080/user-api/todo/690dc6ba0df7a9ec2cb1f679
Content-Type: application/json

{
   
    "taskName":"read",
    "description":"test"

   
}


### Update todo
PUT http://localhost:8080/user-api/todo?userId=690d74b1233a67aef0416f66&taskId=690d97448a1ee3a56b2f4527
Content-Type: application/json

{
   
    "taskName":"dance"
   

   
}

### Delete todo by id
PUT http://localhost:8080/user-api/delete-todo?userId=690d74b1233a67aef0416f66&taskId=690d97448a1ee3a56b2f4527

### logout
GET http://localhost:8080/user-api/logout

### test
GET http://localhost:8080/user-api/test
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjY5MGQ2YjRhMmFiNzJiYWY4NzIyNDg0NyIsIm5hbWUiOiJyYXZpIiwiZW1haWwiOiJyYXZpMTNAbWFpbC5jb20iLCJ0b2RvcyI6W10sImNyZWF0ZWRBdCI6IjIwMjUtMTEtMDdUMDM6NDU6MTQuMDMxWiIsInVwZGF0ZWRBdCI6IjIwMjUtMTEtMDdUMDM6NDU6MTQuMDMxWiJ9LCJpYXQiOjE3NjI0ODczODEsImV4cCI6MTc2MjQ4NzQxMX0.2-d3YzhFY9goiQNPTf6onEROdyFRCpuBM6vWUf5N_rU; Max-Age=30; Path=/; Expires=Fri, 07 Nov 2025 03:50:11 GMT; HttpOnly; Secure; SameSite=None